# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d55SFKBttonaCETdCLj8TTe83v8PtB_G
"""

a=78
b=989
c=a+b
print(c)